(function(g){var window=this;'use strict';var b3Q=function(l,c){if(!Number.isFinite(l))return String(l);l=String(l);var Y=l.indexOf(".");Y===-1&&(Y=l.length);var X=l[0]==="-"?"-":"";X&&(l=l.substring(1));return X+(0,g.bF7)("0",Math.max(0,c-Y))+l},qQ7=function(){return{J:"svg",
S:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},Y:[{J:"path",S:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},a9M=function(){return{J:"svg",
S:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},Y:[{J:"path",S:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},pbQ=function(l){typeof l==="number"?(this.date=Nbe(l,0,1),RK(this,1)):g.gy(l)?(this.date=Nbe(l.getFullYear(),l.getMonth(),l.getDate()),RK(this,l.getDate())):(this.date=new Date(g.cV()),l=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),RK(this,l))},Nbe=function(l,c,Y){c=new Date(l,c,Y);
l>=0&&l<100&&c.setFullYear(c.getFullYear()-1900);return c},RK=function(l,c){l.getDate()!=c&&l.date.setUTCHours(l.date.getUTCHours()+(l.getDate()<c?1:-1))},iK=function(l,c){g.Mu.call(this,l,{J:"div",
X:"ytp-reminder-menu",S:{role:"menu",tabindex:"-1"},Y:[{J:"div",X:"ytp-reminder-menu-contents",Y:[{J:"div",X:"ytp-reminder-menu-items"}]}]},100,!0);this.D=c;this.K=[];this.menuPopupRenderer=void 0;this.items=this.wf("ytp-reminder-menu-items");this.hide()},RVa=function(l){return(l.menuPopupRenderer&&l.menuPopupRenderer.items||[]).reduce(function(c,Y){Y&&Y.menuServiceItemRenderer&&c.push(Y.menuServiceItemRenderer);
return c},[])},SY=function(l){g.B.call(this,{J:"div",
Y:[{J:"button",WU:["ytp-offline-slate-button","ytp-button"],Y:[{J:"div",X:"ytp-offline-slate-button-icon",Qf:"{{icon}}"},{J:"div",X:"ytp-offline-slate-button-text",Qf:"{{text}}"}]}]});this.V=l;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.G=void 0;this.T=this.D=null;(this.W=this.wf("ytp-offline-slate-button"))&&this.Z(this.W,"click",this.C);this.hide()},SQQ=function(l,c,Y){!l.toggleButtonRenderer&&c&&c.toggleButtonRenderer?l.toggleButtonRenderer=c.toggleButtonRenderer:
c&&c.toggleButtonRenderer||(l.toggleButtonRenderer=null);
!l.upcomingEventReminderButtonRenderer&&Y&&g.m(Y,i3V)?l.upcomingEventReminderButtonRenderer=g.m(Y,i3V):Y&&g.m(Y,i3V)||(l.upcomingEventReminderButtonRenderer=null);v$(l)},v$=function(l){if(l.toggleButtonRenderer){var c=l.toggleButtonRenderer;
if(c.isToggled){var Y=c.toggledText?g.qf(c.toggledText):"";l.update({text:Y,icon:v_i(c.toggledIcon)})}else Y=c.defaultText?g.qf(c.defaultText):"",l.update({text:Y,icon:v_i(c.defaultIcon)});l.show()}else l.upcomingEventReminderButtonRenderer?(c=xgV(l))?(Y=c.text?g.qf(c.text):"",l.update({text:Y,icon:v_i(c.icon)}),l.show()):l.hide():l.hide()},n_7=function(l,c,Y){l.T||(l.T=new g.cw(l.V.L().Qg));
var X={context:g.U1(l.T.config_||g.t0())};g.nj()&&(X.context.clientScreenNonce=g.nj());X.params=Y;g.Y4(l.T,c,X,{timeout:5E3,onSuccess:function(){l.upcomingEventReminderButtonRenderer&&l.G&&(l.upcomingEventReminderButtonRenderer.currentState=l.G,l.G=void 0)},
onError:function(){zVN(l)},
onTimeout:function(){zVN(l)}})},zVN=function(l){l.toggleButtonRenderer?(l.toggleButtonRenderer.isToggled=!l.toggleButtonRenderer.isToggled,v$(l)):l.upcomingEventReminderButtonRenderer&&(l.G=void 0,v$(l))},v_i=function(l){if(!l)return null;
switch(l.iconType){case "NOTIFICATIONS":return qQ7();case "NOTIFICATIONS_NONE":return a9M();case "NOTIFICATIONS_ACTIVE":return g.xQ();default:return null}},xgV=function(l){if(!l.upcomingEventReminderButtonRenderer)return null;
var c=l.G||l.upcomingEventReminderButtonRenderer.currentState;l=g.b(l.upcomingEventReminderButtonRenderer.states||[]);for(var Y=l.next();!Y.done;Y=l.next())if((Y=g.m(Y.value,hVU))&&Y.state===c&&Y.button&&g.m(Y.button,g.oY))return g.m(Y.button,g.oY);return null},H3U=function(l){g.B.call(this,{J:"div",
X:"ytp-offline-slate",Y:[{J:"div",X:"ytp-offline-slate-background"},{J:"div",X:"ytp-offline-slate-bar",Y:[{J:"span",X:"ytp-offline-slate-icon",Y:[{J:"svg",S:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},Y:[{J:"path",S:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{J:"circle",S:{cx:"12",cy:"12",r:"3"}}]}]},{J:"span",X:"ytp-offline-slate-messages",Y:[{J:"div",X:"ytp-offline-slate-main-text",S:{"aria-label":"{{label}}"},Qf:"{{mainText}}"},{J:"div",X:"ytp-offline-slate-subtitle-text",Qf:"{{subtitleText}}"}]},{J:"span",X:"ytp-offline-slate-buttons"}]},{J:"button",WU:["ytp-offline-slate-close-button","ytp-button"],Y:[g.Rw()]},{J:"button",WU:["ytp-offline-slate-open-button","ytp-button"],Y:[g.ps()]}]});var c=this;this.api=l;this.D=this.G=null;this.background=this.wf("ytp-offline-slate-background");
this.K=this.wf("ytp-offline-slate-bar");this.W=new g.gY(function(){g.Jj(c.K,"ytp-offline-slate-bar-fade")},15E3);
this.C=!1;this.T=new g.gY(function(){g.Jj(c.element,"ytp-offline-slate-collapsed")},15E3);
g.Z(this,this.T);g.Z(this,this.W);this.countdownTimer=new g.gY(this.U2,1E3,this);this.Z(l,"presentingplayerstatechange",this.n_);this.Z(l,"livestatedata",this.df);this.Z(this.wf("ytp-offline-slate-close-button"),"click",function(){g.Jj(c.element,"ytp-offline-slate-collapsed")});
this.Z(this.wf("ytp-offline-slate-open-button"),"click",function(){g.yu(c.element,"ytp-offline-slate-collapsed")});
this.hide();l=this.getVideoData();l.getPlayerResponse()&&(l=l.getPlayerResponse().playabilityStatus)&&this.df(l);l=this.api.getPresentingPlayerType()===8&&!this.getVideoData().Zs;var Y=this.api.getPresentingPlayerType()===8;g.DK(this.element,"ytp-offline-slate-premiere-trailer",l);g.DK(this.element,"ytp-offline-slate-hide-background",Y)},wba=function(l,c,Y){if(c){var X=c.subtitleText!=null?g.qf(c.subtitleText):"";
Y=Y?Y:c.mainText!=null?g.qf(c.mainText):"";var k,r,e,d;c=(d=(k=c.mainText)==null?void 0:(r=k.accessibility)==null?void 0:(e=r.accessibilityData)==null?void 0:e.label)!=null?d:Y;l.update({mainText:Y,subtitleText:X,label:c});g.DK(l.element,"ytp-offline-slate-single-text-line",!X);g.DK(l.K,"ytp-offline-slate-bar-hidden",!Y&&!X)}},xd=function(l,c){var Y=(0,g.nb)();
this.module="heartbeat";this.trigger=l;this.D=c;this.K=Y},Cd7=function(l){g.GH.call(this,l);
var c=this;this.C=!1;this.U=0;this.N=!1;this.G=new g.gY(function(){K4E(c)},0);
this.D=this.heartbeatParams=null;this.T=!1;this.W=new g.hG(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.AJ=new g.cw(void 0);this.attestationResponse=Promise.resolve(void 0);this.j=Promise.resolve(void 0);this.utcOffsetMinutes=-(new pbQ).getTimezoneOffset();this.K=new g.Cr(this);g.Z(this,this.G);g.Z(this,this.K);TbN(this);jTa(this);this.K.Z(l,"heartbeatparams",this.un);this.K.Z(l,"presentingplayerstatechange",this.Jk);this.K.Z(l,"videoplayerreset",this.PQ);this.K.Z(l,g.Jv("heartbeat"),
this.onCueRangeEnter);this.T&&this.D&&VDQ(this,void 0,this.D);var Y=new g.r8(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),X=new g.r8(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});l.jk([Y,X]);o_c(this)},o_c=function(l){var c=l.getVideoData();
!c.B("use_rta_for_player")&&c.Nt&&(c=c.botguardData)&&g.$G(c,l.player.L())},Z3E=function(l){var c,Y;
return g.H(function(X){if(X.D==1)return g.n(X,g.pwn(),2);if(!X.G)return l.sequenceNumber>=3?X.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):X.return(void 0);c=l.getVideoData();Y={};return X.return(g.NIn((Y.cpn=c.clientPlaybackNonce,Y.encryptedVideoId=c.videoId||"",Y),1500))})},TbN=function(l){var c=l.getVideoData();
if(c.Nt)if(c.B("use_rta_for_player"))l.attestationResponse=Z3E(l);else if(c=new g.SPr(c),g.Vw.isInitialized()||l.sequenceNumber>=3){var Y=Promise,X=Y.resolve,k=null;if(c.videoData.uI){var r=g.vur(c);if(r){k={};var e={};r=r.split("&");r=g.b(r);for(var d=r.next();!d.done;d=r.next())d=d.value.split("="),d.length===2&&(e[d[0]]=d[1]);e.r1a&&(k.webResponse=e.r1a);e.r1c&&(k.error=$gU[Number(e.r1c)]);k.challenge=c.videoData.uI}}l.attestationResponse=X.call(Y,k||void 0)}},QTc=function(l){var c=l.getVideoData();
if(!g.NB(l.getVideoData())||c.i_)return!1;if(c.N){l=c.N.flavor==="playready"&&c.B("html5_innertube_heartbeats_for_playready");var Y=c.N.flavor==="widevine"&&c.B("html5_innertube_heartbeats_for_widevine");c=g.Qs(c.N)&&c.B("html5_innertube_heartbeats_for_fairplay");return!(l||Y||c)}return!0},mgc=function(l){if(QTc(l))return!!l.heartbeatParams;
var c=l.getVideoData();return!g.NB(l.getVideoData())||c.l5||c.Fz?!!c.heartbeatToken:!1},zC=function(l,c){if(!l.G.isActive()&&l.C){var Y=l.getVideoData();
if(mgc(l)||Y.isLivePlayback){if(c===void 0)if(l.N)if(l.T)c=7500;else{var X;c=((X=l.heartbeatParams)==null?0:X.interval)?l.heartbeatParams.interval*1E3:l.getVideoData().P6||6E4}else c=1E3;l.G.start(c)}}},Bbc=function(l,c,Y){c.IA&&(Y=g.Il(Y,{internalipoverride:c.IA}));
var X={cpn:c.clientPlaybackNonce};c.contextParams&&(X.context_params=c.contextParams);c.Pu&&(X.kpt=c.Pu);Y=g.Il(Y,X);g.xm(Y,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(k){if(!l.G.isActive()&&nT(l)){l.W.reset();l.sequenceNumber++;k=k.responseText;var r=W4L(k);if(r){l.player.cU("onHeartbeat",r);var e=r.status==="ok"?r.stop_heartbeat?2:0:r.status==="stop"?1:r.status==="live_stream_offline"?0:-1}else e=(e=k.match(MD7))?e[1]==="0"?0:1:-1;sTe(l,void 0,r,k,e)}},
onError:function(k){nT(l)&&hK(l,!0,"net-"+k.status)},
onTimeout:function(){nT(l)&&hK(l,!0,"timeout")},
withCredentials:!0})},K4E=function(l){var c,Y;
g.H(function(X){c=l.player.L();Y=l.getVideoData();if(!nT(l))return X.return();if(QTc(l))return L4V(l,c,Y),X.kT(0);TbN(l);return g.n(X,E_L(l,c,Y),0)})},L4V=function(l,c,Y){var X;
if((X=l.heartbeatParams)!=null&&X.url){var k=g.Il(l.heartbeatParams.url,{request_id:g.vmg()});Y.Kh&&(k=g.Il(k,{vvt:Y.Kh}),Y.mdxEnvironment&&(k=g.Il(k,{mdx_environment:Y.mdxEnvironment})));g.ra(c,Y.oauthToken).then(function(r){r&&(k=g.Il(k,{access_token:r}));Bbc(l,Y,k)})}},nT=function(l){var c=l.getVideoData();
return l.player.getPresentingPlayerType()===3||g.L(l.player.getPlayerStateObject(l.getPlayerType()),4)?!1:mgc(l)||c.isLivePlayback?!0:(H$(l),!1)},E_L=function(l,c,Y){var X,k,r,e,d,y,O,D,t,U,G,f,a,p,S,x,h,K,Q,lc;
return g.H(function(E){if(E.D==1)return X="player/heartbeat",r={videoId:Y.videoId,sequenceNumber:l.sequenceNumber,heartbeatServerData:(k=l.Kh)!=null?k:Y.heartbeatServerData},l.j=l.attestationResponse,Y.Nt?g.n(E,l.j,3):E.kT(2);E.D!=2&&(r.attestationResponse=E.G);e=g.dP(Y);y=(d=e.client)!=null?d:{};y.utcOffsetMinutes=l.utcOffsetMinutes;r.context=e;r.cpn=Y.clientPlaybackNonce;if(O=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)y.timeZone=O;D={heartbeatChecks:[]};
if(t=Y.getPlayerResponse())Y.heartbeatToken&&(r.heartbeatToken=Y.heartbeatToken),(U=t.playabilityStatus)&&(G=U.liveStreamability)&&G.liveStreamabilityRenderer&&D.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");Y.heartbeatToken&&D.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.xu(c)&&(D.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),f=g_c(l),a={},f!==null&&(a.clientPlayerPositionUtcMillis=f),S=(p=l.player.wB())==null?void 0:g.x3(p),h=((x=S)==null?void 0:x.freePreviewWatchedDuration)||
0,h>0&&(a.freePreviewWatchedDuration={seconds:""+h}),D.unpluggedParams=a);r.heartbeatRequestParams=D;Y.isLivePlayback?(K=g_c(l),K!==null&&(r.playbackState||(r.playbackState={}),r.playbackState.playbackPosition={utcTimeMillis:K})):c.B("enable_heartbeat_vod_playback_position")&&(Q=uQc(l),Q!==null&&(r.playbackState||(r.playbackState={}),r.playbackState.playbackPosition={streamTimeMillis:Q}));l.player.publish("heartbeatRequest",r);lc={timeout:3E4,onSuccess:function(kv){if(!l.G.isActive()&&nT(l)){var Jg=
l.getVideoData(),I=Jg.Nt&&l.j==null,W;Jg.Nt=!((W=kv.heartbeatAttestationConfig)==null||!W.requiresAttestation)||I;I=kv.playabilityStatus;W=JSON.stringify(I)||"{}";kv.authenticationMismatch&&l.player.Gz("authshear",{});var F=-1;var q=kv.playabilityStatus;q&&(l.player.cU("onHeartbeat",q),q.status==="OK"?F=kv.stopHeartbeat?2:0:q.status==="UNPLAYABLE"?F=1:q.status==="LIVE_STREAM_OFFLINE"&&(F=0));l.sequenceNumber&&F===-1||l.W.reset();l.sequenceNumber++;kv.heartbeatServerData&&(l.Kh=kv.heartbeatServerData);
Jg.A1=kv;(q=kv.playerCueRangeSet)&&g.F6(Jg,q);kv.playerCueRanges&&kv.playerCueRanges.length>0&&(Jg.cueRanges=kv.playerCueRanges);var M,mK;((M=kv.progressBarConfig)==null?0:M.progressBarStartPosition)&&((mK=kv.progressBarConfig)==null?0:mK.progressBarEndPosition)&&(Jg.progressBarStartPosition=kv.progressBarConfig.progressBarStartPosition,Jg.progressBarEndPosition=kv.progressBarConfig.progressBarEndPosition);Jg.compositeLiveIngestionOffsetToken=kv.compositeLiveIngestionOffsetToken;kv.compositeLiveStatusToken!==
Jg.compositeLiveStatusToken&&(Jg.compositeLiveStatusToken=kv.compositeLiveStatusToken);Jg.publish("dataupdated");sTe(l,kv,I,W,F)}},
onError:function(kv){nT(l)&&hK(l,!0,"net-"+kv.status)},
onTimeout:function(){nT(l)&&hK(l,!0,"timeout")}};
g.ra(c,g.mj(Y)).then(function(kv){kv&&(lc.wq="Bearer "+kv);g.Y4(l.AJ,X,r,lc)});
g.pL(E)})},sTe=function(l,c,Y,X,k){k===-1?(Y="decode "+g.NM(X,3),hK(l,!1,Y)):k===2?(H$(l),l.N=!0):(l.U=0,l.G.stop(),k===1?(l.N=!1,Y&&Y.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&l.player.Qu(!0),k="pe."+(Y==null?void 0:Y.errorCode)+";ps."+(Y==null?void 0:Y.status),l.player.dT("heartbeat.stop",2,l.xu(X),k),g.Oq("heartbeatActionPlayerHalted",ARQ(Y)),(c==null?0:c.videoTransitionEndpoint)&&Y&&(c=c.videoTransitionEndpoint,(X=g.m(c,g.lG))&&F4e(l,X,Y,{itct:c==null?void 0:c.clickTrackingParams}))):(l.N=
!0,X=0,l.T&&Y&&(X=VDQ(l,c,Y),l.player.publish("livestatedata",Y)),X?zC(l,X):zC(l)))},VDQ=function(l,c,Y){var X=Y.liveStreamability&&Y.liveStreamability.liveStreamabilityRenderer,k=!(!X||!(X.switchStreamsImmediately||X.transitionTiming&&X.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
c=I96(l,c,X);var r=l.getVideoData(),e=l.player.getPlayerStateObject(l.getPlayerType()),d=e.isPlaying()&&!g.nw(r)&&!l.player.isAtLiveHead(l.getPlayerType());if(r.L().EV()){var y,O=((y=l.player.Vx())==null?void 0:y.jC())||{};O.status=Y.status||"";O.dvr=""+ +d;O["switch"]=""+ +k;O.ended=""+ +!(!X||!X.displayEndscreen);l.player.Gz("heartbeat",O)}if(d&&!k)return c;k=X&&X.streamTransitionEndpoint&&g.m(X.streamTransitionEndpoint,g.lG);if((X&&X.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")l.getVideoData().transitionEndpointAtEndOfStream=
k;else if(k&&F4e(l,k,Y))return c;if(Y.status.toUpperCase()==="OK"){k=X&&X.broadcastId;y=l.D&&l.D.liveStreamability&&l.D.liveStreamability.liveStreamabilityRenderer&&l.D.liveStreamability.liveStreamabilityRenderer.broadcastId;d=k!==y&&k!=null;if(!g.S8(r)||d){var D={video_id:r.videoId};r.Qn&&(D.is_live_destination="1");D.disable_watch_next=!0;D.raw_watch_next_response=r.getWatchNextResponse();D.autonav_state=r.autonavState;D.oauth_token=r.oauthToken;D.force_gvi=r.bH;D.jV=r.jV;r.W&&(D.vss_credentials_token=
r.W,D.vss_credentials_token_type=r.CP);r.Kh&&(D.vvt=r.Kh);X=void 0;g.S8(r)?d&&(X=new xd("broadcastIdChanged",y+","+k),l.lY("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",Y)):(k&&(X=new xd("formatsReceived",""+k)),l.lY("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",Y));l.player.loadVideoByPlayerVars(D,void 0,void 0,void 0,X);return c}l.player.Qd("heartbeat",l.getPlayerType())}X&&X.displayEndscreen&&(l.offlineSlate?
(l=l.offlineSlate,l.C=!0,l.Ag&&l.api.Bq()):e.isBuffering()&&(r=((D=l.player.Vx())==null?void 0:D.jC())||{},l.player.Gz("hbse",r,!0),l.player.Bq(),l.player.cU("onLiveMediaEnded",Y)));return c},I96=function(l,c,Y){return l.player.B("web_player_use_heartbeat_poll_delay_ms")&&(l=Number(c==null?void 0:c.pollDelayMs))?l:(Y=Number(Y==null?void 0:Y.pollDelayMs))?Y:0},hK=function(l,c,Y){var X=l.player.L();
if(!l.G.isActive()){l.G.stop();l.U++;var k=c?"heartbeat.net":"heartbeat.servererror";var r=l.getVideoData();if(r.RJ||c&&!g.NB(l.getVideoData())&&!mgc(l)&&r.isLivePlayback)r=!1;else{var e,d;((d=l.heartbeatParams)==null?0:d.retries)?e=l.heartbeatParams.retries:e=r.Vn||5;r=l.U>=e}r?(g.Oq("heartbeatActionPlayerHalted",c?{enforcedPolicyToHaltOnNetworkFailure:!0}:ARQ()),(c=l.getVideoData())&&c.isLivePlayback?l.player.dT(k,1,"Reprodu\u00e7\u00e3o de v\u00eddeo interrompida. Tente novamente.",Y):l.player.dT(k,
1,"Ocorreu um erro ao licenciar este v\u00eddeo.",Y)):(X.B("html5_report_non_fatal_heartbeat_error")&&l.player.tG(k,{msg:Y}),zC(l,l.W.getValue()),g.Hs(l.W))}},ARQ=function(l){var c={enforcedPolicyToHaltOnNetworkFailure:!1};
l&&(c.serializedServerContext=l.additionalLoggingData);return c},H$=function(l){l.U=0;
l.G.stop();l.N=!1;l.sequenceNumber=0},jTa=function(l){var c=l.getVideoData(),Y=l.player.L();
if(c.isLivePlayback)if(g.Xf(Y.N)){l.T=!0;l.C=!0;if(!g.nz(Y)||g.xu(Y))l.offlineSlate=new H3U(l.player),g.Z(l,l.offlineSlate),g.oD(l.player,l.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(l.D=c.playabilityStatus);var X;((X=l.D)==null?void 0:X.status)!=="UNPLAYABLE"&&(l.D?(X=I96(l,void 0,l.D.liveStreamability&&l.D.liveStreamability.liveStreamabilityRenderer))?zC(l,X):zC(l,7500):zC(l,1E3))}else l.player.dT("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.AE(c.xT,"heartbeat")&&l.player.Qd("heartbeat",l.getPlayerType())},F4e=function(l,c,Y,X){var k=c&&c.videoId;
return k?(l.player.vn(k,Object.assign({},{autonav:"1"},X||{}),void 0,!0,!0,c,g.mj(l.getVideoData())),l.lY("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",Y),!0):!1},g_c=function(l){return(l=l.player.getProgressState(l.getPlayerType()).ingestionTime)&&isFinite(l)?""+Math.floor(l*1E3):null},uQc=function(l){return(l=l.player.getCurrentTime(l.getPlayerType()))&&isFinite(l)?""+Math.floor(l*1E3):null},W4L=function(l){try{var c=JSON.parse(l);
return c!=null?c:void 0}catch(Y){}},lr6={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
lr6={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","depois de Cristo"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),STANDALONEMONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),SHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),STANDALONESHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),
WEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),STANDALONESHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),NARROWWEEKDAYS:"DSTQQSS".split(""),STANDALONENARROWWEEKDAYS:"DSTQQSS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1\u00ba trimestre",
"2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d 'de' MMM 'de' y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} '\u00e0s' {0}","{1} '\u00e0s' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var $gU=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],cYN={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.J=pbQ.prototype;g.J.HO=lr6.FIRSTDAYOFWEEK;g.J.yl=lr6.FIRSTWEEKCUTOFFDAY;
g.J.clone=function(){var l=new pbQ(this.date);l.HO=this.HO;l.yl=this.yl;return l};
g.J.getFullYear=function(){return this.date.getFullYear()};
g.J.getYear=function(){return this.getFullYear()};
g.J.getMonth=function(){return this.date.getMonth()};
g.J.getDate=function(){return this.date.getDate()};
g.J.getTime=function(){return this.date.getTime()};
g.J.getDay=function(){return this.date.getDay()};
g.J.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.J.getUTCMonth=function(){return this.date.getUTCMonth()};
g.J.getUTCDate=function(){return this.date.getUTCDate()};
g.J.getUTCDay=function(){return this.date.getDay()};
g.J.getUTCHours=function(){return this.date.getUTCHours()};
g.J.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.J.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.J.set=function(l){this.date=new Date(l.getFullYear(),l.getMonth(),l.getDate())};
g.J.setFullYear=function(l){this.date.setFullYear(l)};
g.J.setYear=function(l){this.setFullYear(l)};
g.J.setMonth=function(l){this.date.setMonth(l)};
g.J.setDate=function(l){this.date.setDate(l)};
g.J.setTime=function(l){this.date.setTime(l)};
g.J.setUTCFullYear=function(l){this.date.setUTCFullYear(l)};
g.J.setUTCMonth=function(l){this.date.setUTCMonth(l)};
g.J.setUTCDate=function(l){this.date.setUTCDate(l)};
g.J.add=function(l){if(l.years||l.months){var c=this.getMonth()+l.months+l.years*12,Y=this.getYear()+Math.floor(c/12);c%=12;c<0&&(c+=12);a:{switch(c){case 1:var X=Y%4!=0||Y%100==0&&Y%400!=0?28:29;break a;case 5:case 8:case 10:case 3:X=30;break a}X=31}X=Math.min(X,this.getDate());this.setDate(1);this.setFullYear(Y);this.setMonth(c);this.setDate(X)}l.days&&(Y=this.getYear(),c=Y>=0&&Y<=99?-1900:0,l=new Date((new Date(Y,this.getMonth(),this.getDate(),12)).getTime()+l.days*864E5),this.setDate(1),this.setFullYear(l.getFullYear()+
c),this.setMonth(l.getMonth()),this.setDate(l.getDate()),RK(this,l.getDate()))};
g.J.HI=function(l){return!(!l||this.getYear()!=l.getYear()||this.getMonth()!=l.getMonth()||this.getDate()!=l.getDate())};
g.J.toString=function(){var l=this.getFullYear(),c=l<0?"-":l>=1E4?"+":"";return[c+b3Q(Math.abs(l),c?6:4),b3Q(this.getMonth()+1,2),b3Q(this.getDate(),2)].join("")+""};
g.J.valueOf=function(){return this.date.valueOf()};var YU7=new g.zL("addUpcomingEventReminderEndpoint");var XME=new g.zL("removeUpcomingEventReminderEndpoint");var kUE=new g.zL("updateUpcomingEventReminderButtonStateCommand");var i3V=new g.zL("upcomingEventReminderButtonRenderer"),hVU=new g.zL("upcomingEventReminderButtonStateRenderer");g.P(iK,g.Mu);
iK.prototype.updateMenuItems=function(){var l=this,c=RVa(this),Y=0;Y=0;for(var X={};Y<c.length;X={R0:void 0},Y++){var k=this.K[Y];k||(k=new g.B({J:"div",X:"ytp-reminder-menu-item",S:{role:"menuitem",tabindex:"0"},Y:[{J:"div",X:"ytp-reminder-menu-item-icon",Qf:"{{icon}}"},{J:"div",X:"ytp-reminder-menu-item-label",Qf:"{{text}}"}]}),X.R0=Y,k.listen("click",function(e){return function(){var d=e.R0;l.sV();d=RVa(l)[d];l.publish("reminderMenuItemClicked",d.serviceEndpoint||d.command)}}(X)),k.Vf(this.items),
this.K[Y]=k);
var r=c[Y];X=null;switch(r.icon&&r.icon.iconType){case "NOTIFICATIONS":X=qQ7();break;case "NOTIFICATIONS_NONE":X=a9M();break;case "NOTIFICATIONS_ACTIVE":X=g.xQ()}r=r.text?g.qf(r.text):"";k.update({icon:X,text:r})}for(;Y<this.K.length;)this.K.pop().dispose();Y===0?this.sV():this.YF(this.D)};
iK.prototype.hide=function(){this.D&&this.D.removeAttribute("aria-haspopup");g.Mu.prototype.hide.call(this)};
iK.prototype.show=function(){this.D&&this.D.setAttribute("aria-haspopup","true");g.Mu.prototype.show.call(this)};
iK.prototype.Tz=function(){g.ON(this.K);g.Mu.prototype.Tz.call(this)};g.P(SY,g.B);
SY.prototype.C=function(){if(this.toggleButtonRenderer){var l=this.toggleButtonRenderer;l.isToggled?this.K(l.toggledServiceEndpoint):this.K(l.defaultServiceEndpoint);l.isToggled=!l.isToggled;v$(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.D&&this.D.Ag)this.D.sV();else{var c=xgV(this);c&&this.K(c.serviceEndpoint||c.command);c=((l=g.m(c==null?void 0:c.command,g.qI))==null?void 0:l.commands)||[];a:{l=g.b(c);for(var Y=l.next();!Y.done;Y=l.next()){var X=c=void 0;if(Y=(c=g.m(Y.value,g.xML))==
null?void 0:(X=c.popup)==null?void 0:X.menuPopupRenderer){l=Y;break a}}l=void 0}this.D||(this.D=new iK(this.V,this.W),this.D.Vf(this.element),g.Z(this,this.D),this.D.subscribe("reminderMenuItemClicked",this.K,this));c=this.D;c.menuPopupRenderer=l;c.updateMenuItems()}};
SY.prototype.K=function(l){var c=g.m(l,YU7),Y=g.m(l,XME);if(l&&(c||Y)){if(c){var X=c;var k="notification/add_upcoming_event_reminder"}else Y&&(X=Y,k="notification/remove_upcoming_event_reminder");if(k&&X&&X.params)for(n_7(this,k,X.params),l=g.b(X.commands||[]),c=l.next();!c.done;c=l.next())if((c=c.value)&&g.m(c,kUE)){this.G=g.m(c,kUE).state;v$(this);break}}};g.P(H3U,g.B);g.J=H3U.prototype;g.J.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.J.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.J.df=function(l){var c,Y,X=l==null?void 0:(c=l.liveStreamability)==null?void 0:(Y=c.liveStreamabilityRenderer)==null?void 0:Y.offlineSlate;if(X){this.G=l;c=X.liveStreamOfflineSlateRenderer;c.canShowCountdown?this.U2():wba(this,c);var k,r,e,d;if(Y=l==null?void 0:(k=l.liveStreamability)==null?void 0:(r=k.liveStreamabilityRenderer)==null?void 0:(e=r.offlineSlate)==null?void 0:(d=e.liveStreamOfflineSlateRenderer)==null?void 0:d.thumbnail){k=0;r=null;e=Y.thumbnails;for(d=0;d<e.length;d++)e[d].width>
k&&(k=e[d].width||0,r=e[d].url);r&&(this.background.style.backgroundImage="url("+r+")")}else this.background.style.backgroundImage="";c.actionButtons||c.reminderButton?(this.D||(this.D=new SY(this.api),this.D.Vf(this.wf("ytp-offline-slate-buttons")),g.Z(this,this.D)),SQQ(this.D,c.actionButtons&&c.actionButtons[0],c.reminderButton)):this.D&&SQQ(this.D,null,null);this.G=l}else this.G=null;this.n_()};
g.J.n_=function(l){if(this.api.getPresentingPlayerType()===8)var c=!0;else{var Y=this.api.getPlayerStateObject(),X=this.getVideoData();c=X.isLivePlayback&&(Y.isBuffering()||g.L(Y,2)||g.L(Y,64));var k=X.autonavState===2&&g.L(Y,2);Y=Y.isPlaying()&&!g.nw(X)&&!this.api.isAtLiveHead(void 0,!0);c=c&&!Y&&!k}c&&this.G?this.Ag?(l==null?0:g.PE(l,2))&&!this.getVideoData().Zs&&(g.yu(this.element,"ytp-offline-slate-collapsed"),this.T.stop(),g.yu(this.K,"ytp-offline-slate-bar-fade"),this.W.start()):(this.show(),
this.T.start(),this.api.publish("offlineslatestatechange"),this.C&&this.api.Bq()):this.Ag&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.J.U2=function(){var l,c,Y,X,k=(l=this.G)==null?void 0:(c=l.liveStreamability)==null?void 0:(Y=c.liveStreamabilityRenderer)==null?void 0:(X=Y.offlineSlate)==null?void 0:X.liveStreamOfflineSlateRenderer;k&&(l=Math.floor(g.cV()/1E3),c=k.canShowCountdown&&Number(k.scheduledStartTime),!c||c<=l?(wba(this,k),this.countdownTimer.stop()):(wba(this,k,g.vE(c-l)),g.uf(this.countdownTimer)))};
g.J.Tz=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.B.prototype.Tz.call(this)};xd.prototype.G=function(l){return this.trigger&&l.trigger?this.module===l.module&&this.trigger===l.trigger&&this.D===l.D:!1};
xd.prototype.isExpired=function(){return(0,g.nb)()-this.K>6E4};
xd.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.D};g.P(Cd7,g.GH);g.J=Cd7.prototype;g.J.Tz=function(){H$(this);this.player.EU("heartbeat");g.GH.prototype.Tz.call(this)};
g.J.onCueRangeEnter=function(){this.C=!0;zC(this,2E3)};
g.J.un=function(l){this.heartbeatParams=l;zC(this,2E3)};
g.J.Jk=function(l){var c;this.player.getPresentingPlayerType()!==8&&((c=this.D)==null?void 0:c.status)!=="UNPLAYABLE"&&(g.L(l.state,2)||g.L(l.state,64)?(H$(this),this.T&&(this.C=!0,zC(this,1E3))):(g.L(l.state,1)||g.L(l.state,8))&&zC(this,2E3))};
g.J.PQ=function(){this.player.getPresentingPlayerType()!==3&&zC(this,2E3)};
g.J.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.J.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.J.Pn=function(l){switch(l){case 4:case 3:return!1}return!0};
g.J.lY=function(l,c,Y){l={trigger:l,reason:c};Y&&(l.serializedServerContext=Y.additionalLoggingData);g.Oq("heartbeatActionPlayerTransitioned",l)};
g.J.xu=function(l){var c="LICENSE",Y=W4L(l);if(Y)return Y.reason||g.oS[c]||"";if(l=l.match(MD7))if(l=Number(l[1]))c=(c=cYN[l.toString()])?c:"LICENSE";return g.oS[c]||""};
g.J.Ho=function(){return!!this.offlineSlate&&this.offlineSlate.Ag};
var MD7=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.U$("heartbeat",Cd7);})(_yt_player);
